# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "go-outline-unstable-${version}";
  version = "2017-08-03";
  rev = "9e9d089bb61a5ce4f8e0c8d8dc5b4e41b0e02a48";

  goPackagePath = "github.com/ramya-rao-a/go-outline";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/ramya-rao-a/go-outline.git";
    sha256 = "0kbkv4d6q9w0d41m00sqdm10l0sg56mv8y6rmidqs152mm2w13x0";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
