# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gomodifytags-unstable-${version}";
  version = "2017-11-11";
  rev = "edb7aeaa4d5f3c540621f1d605028e5ba31dcf5b";

  goPackagePath = "github.com/fatih/gomodifytags";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/fatih/gomodifytags.git";
    sha256 = "1iqgzq87zvrg9dma70nx7li5dzid7mw5m8dvrxr8n0qnaxg74jg5";
  };

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
