# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "impl-unstable-${version}";
  version = "2017-08-01";
  rev = "77a11c2c450290890287c32ed208f60debca1805";

  goPackagePath = "github.com/josharian/impl";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/josharian/impl.git";
    sha256 = "1rklpvf0gb12dw8j7hwgsd9xr6mqxq3f77khpp2cyzn38x5q31nl";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
