# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "forego-unstable-${version}";
  version = "2017-03-27";
  rev = "9cd74005149b389d894e6b49c72972785577ad49";

  goPackagePath = "github.com/ddollar/forego";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/ddollar/forego.git";
    sha256 = "0fanzlxd1q9d3kba07pspfr1ccm8lfk9mlyishnpq2dyfpcinwax";
  };

  #goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
