# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "forego-unstable-${version}";
  version = "2015-03-27";
  rev = "5d1163795c51e107d7f75532cb650cb7bf39672c";

  goPackagePath = "github.com/ddollar/forego";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/udsholt/forego.git";
    sha256 = "0sjrqb6gqhdai914nsw6l1vncfasp2x4bwil713ibih4bw0jdi4c";
  };

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}

