# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "go-torch-unstable-${version}";
  version = "2017-08-24";
  rev = "ddbe52cdc30e6a165aee3a634c597e01a235e85e";

  goPackagePath = "github.com/uber/go-torch";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/uber/go-torch.git";
    sha256 = "0x0wkdj5s5qi7zp8frs8989767b1n50mbh38mciqig8km4983bsb";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
