# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/fatih/color";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/color.git";
      rev = "5df930a27be2502f99b292b7cc09ebad4d0891f4";
      sha256 = "1xqwvpn5jkp1xqvv9hx4h7cxrsnamryhy2pszcqpbm28dpd3airb";
    };
  }
  {
    goPackagePath = "github.com/jessevdk/go-flags";
    fetch = {
      type = "git";
      url = "https://github.com/jessevdk/go-flags";
      rev = "f88afde2fa19a30cf50ba4b05b3d13bc6bae3079";
      sha256 = "15mvh5ah5483wdbc9s3iw9xh2svc9l3wnjaacr38ksj5cyzxhcx5";
    };
  }
]
