# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gopkgs-unstable-${version}";
  version = "2017-10-27";
  rev = "117893d0b8ebac48f144b025d3dcf42508eacb06";

  goPackagePath = "github.com/uudashr/gopkgs";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/uudashr/gopkgs.git";
    sha256 = "08yppm6b1p5hyzszncxs8l9nrl83pdcbvh1cmc7cwr9xqcfypdan";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
