# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "rerun-unstable-${version}";
  version = "2017-03-09";
  rev = "fda4b67b37d057b19da8ee6abe7442d2cc9a862e";

  goPackagePath = "github.com/skelterjohn/rerun";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/skelterjohn/rerun.git";
    sha256 = "1qbxmaq1xjwm6qk09gh8wv16qizww5pzmf4j3cl0i2ylxrfaz8zi";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
