# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/howeyc/fsnotify";
    fetch = {
      type = "git";
      url = "https://github.com/howeyc/fsnotify.git";
      rev = "f0c08ee9c60704c1879025f2ae0ff3e000082c13";
      sha256 = "14qg62h5y8m6mvgbyxbx2jvmc8z8spm8i0k862v8a7khkij56h04";
    };
  }
]
