# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
    imports = [ ];

    system.stateVersion = "18.03";

    networking.hostName = "gwyran";

    time.timeZone = "Europe/Copenhagen";

    boot.loader.grub.enable = true;
    boot.loader.grub.version = 2;
    boot.loader.grub.device = "/dev/sda";

    boot.initrd.checkJournalingFS = false;
    boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/16765278-53a4-4d34-94d0-e279523b61f6";
        fsType = "ext4";
    };

    fileSystems."/vboxshare" = {
        fsType = "vboxsf";
        device = "shared";
        options = [ "rw" ];
    };

    swapDevices = [ ];

    nix.maxJobs = lib.mkDefault 1;
    virtualisation.virtualbox.guest.enable = true;

    # Host only network with static ipAddress allowed through firewall
    networking.interfaces.enp0s8.ipv4.addresses = [{ address = "192.168.56.30"; prefixLength = 24; }];
    networking.firewall = {
        enable = true;
        trustedInterfaces = ["enp0s8"];
    };
}


