# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "goreturns-unstable-${version}";
  version = "2017-12-29";
  rev = "e5bd430ebbfbdd93b81837ff965ce4464d26c8d9";

  goPackagePath = "github.com/sqs/goreturns";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/sqs/goreturns.git";
    sha256 = "0z8x744v6x08jjfd34y5c6d0p2v5wa2k6vbm6wjd1sifrjvvn669";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
