# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "goreturns-unstable-${version}";
  version = "2017-10-24";
  rev = "3bdb584fbb61d152552a42d1ad382512f71cf472";

  goPackagePath = "github.com/sqs/goreturns";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/sqs/goreturns.git";
    sha256 = "1ij3xda0qmginjq6lz99qmhivqd1dxpviiv9l1qabyllb5b7xrvz";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
