# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "8cab8a1319f0be9798e7fe78b15da75e5f94b2e9";
      sha256 = "0i9pc3x5az4khs249ah7d2pclhzymdxwx8xsj0kwg9zhxgv9ii4f";
    };
  }
]
