# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "6d70fb2e85323e81c89374331d3d2b93304faa36";
      sha256 = "1cmlz19xbhm775bgmvdiii9avpqjh7vhfcwg96i27yc3c9gfc28j";
    };
  }
]
