# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "gogetdoc-unstable-${version}";
  version = "2017-08-25";
  rev = "5e9025786ffb315e584922516dd50dbb7337514e";

  goPackagePath = "github.com/zmb3/gogetdoc";
  excludedPackages = "testdata";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/zmb3/gogetdoc.git";
    sha256 = "0i0x82123221byz9il2d085xxbpcavi3bgjvyip3nhbp9wx4236k";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
